(function(root){
  'use strict';
  var ns=root.FFVNext=root.FFVNext||{};
  function rememberResult(job,intent){if(job&&job.id)ns.entities.set('generation',String(job.id),Object.assign({},intent||{},job));}
  function nav(label,route){var item=ns.Surfaces.node('button','ff-v2-nav',label);item.type='button';item.dataset.ffV2Route=route;return item;}
  function V2Shell(){this.router=new ns.Router({fallback:'home'});this.resources=new ns.Resources();this.started=false;this.root=null;this.content=null;this.surfaceEpoch=0;this.quoteTimer=null;this.draft={dirty:false};}
  V2Shell.prototype.mount=function(){
    var shell=ns.Surfaces.node('div','ff-v2-root');shell.id='ffV2Root';
    var header=ns.Surfaces.node('header','ff-v2-shellbar');header.appendChild(ns.Surfaces.node('strong','ff-v2-brand','FrameFlow'));
    var primary=ns.Surfaces.node('nav','ff-v2-primary-nav');primary.setAttribute('aria-label','Primary');primary.appendChild(nav('Home','home'));primary.appendChild(nav('Create','create'));primary.appendChild(nav('Browse','browse'));header.appendChild(primary);
    var work=ns.Surfaces.node('nav','ff-v2-work-nav');work.setAttribute('aria-label','Workspace');[['Activity','activity'],['Library','library'],['Sessions','sessions'],['Projects','projects'],['Settings','settings'],['Account','account']].forEach(function(item){work.appendChild(nav(item[0],item[1]));});header.appendChild(work);shell.appendChild(header);
    this.content=ns.Surfaces.node('main','ff-v2-main');this.content.id='ffV2Content';this.content.tabIndex=-1;shell.appendChild(this.content);document.body.appendChild(shell);this.root=shell;
    var legacy=document.getElementById('container');if(legacy)legacy.hidden=true;
  };
  V2Shell.prototype.register=function(){
    var self=this;['home','create','browse','activity','library','sessions','projects','account','settings'].forEach(function(route){self.router.register(route,{
      enter:function(context){var epoch=++self.surfaceEpoch,ctx=Object.assign({},context||{},{isCurrent:function(){return self.started&&epoch===self.surfaceEpoch;}});self.root.dataset.route=route;self.root.querySelectorAll('[data-ff-v2-route]').forEach(function(item){var active=item.dataset.ffV2Route===route;item.classList.toggle('active',active);if(active)item.setAttribute('aria-current','page');else item.removeAttribute('aria-current');});if(!self.routeEnabled(route,ctx))return ns.Surfaces.unavailable(route,self.content);return ns.Surfaces.render(route,self.content,ctx);},
      render:function(){self.content.focus({preventScroll:true});},leave:function(){self.surfaceEpoch++;},dispose:function(){}
    });});
  };
  V2Shell.prototype.routeEnabled=function(route,context){if(route==='home')return ns.flags.enabled('homeV2');if(route==='create'){var mode=context&&context.mode||'image';return ns.flags.enabled(mode==='image'?'createImageV2':mode==='video'?'createVideoV2':'createAudioV2');}if(route==='browse')return ns.flags.enabled('browseV2');if(route==='account'||route==='settings')return ns.flags.enabled('accountV2');return ns.flags.enabled('workSurfacesV2');};
  V2Shell.prototype.message=function(text,type){if(typeof root.showToast==='function')root.showToast(text,type||'info');};
  V2Shell.prototype.resetSensitiveState=function(){clearTimeout(this.quoteTimer);this.draft={dirty:false};this.referenceReturn=null;};
  V2Shell.prototype.refreshReferences=function(){var host=this.content&&this.content.querySelector('.ff-v2-references'),modelSelect=this.content&&this.content.querySelector('[name=modelId]');if(host&&modelSelect)ns.Surfaces.renderReferences(host,ns.models.get(modelSelect.value));};
  V2Shell.prototype.refresh=function(context){if(this.router.current)this.router.go(this.router.current.name,context||this.router.current.context||{});};
  V2Shell.prototype.canLeaveCreate=function(target){if(!this.router.current||this.router.current.name!=='create'||target==='create'||!this.draft.dirty)return true;return !root.confirm||root.confirm('Discard the unsent prompt and references? Active generations will continue.');};
  V2Shell.prototype.showEnhancePreview=function(prompt,status,enhanced){
    var old=this.content.querySelector('.ff-v2-enhance-preview');if(old)old.remove();var box=ns.Surfaces.node('section','ff-v2-enhance-preview');box.appendChild(ns.Surfaces.node('strong','','Enhanced preview'));box.appendChild(ns.Surfaces.node('p','',enhanced));var actions=ns.Surfaces.node('div','ff-v2-actions');var replace=ns.Surfaces.node('button','ff-v2-button','Replace prompt');replace.type='button';var keep=ns.Surfaces.node('button','ff-v2-button','Keep original');keep.type='button';actions.appendChild(replace);actions.appendChild(keep);box.appendChild(actions);status.parentNode.insertBefore(box,status);var original=prompt.value;replace.addEventListener('click',function(){prompt.value=enhanced;this.draft.dirty=true;box.replaceChildren(ns.Surfaces.node('span','','Enhanced prompt applied.'));var undo=ns.Surfaces.node('button','ff-v2-button','Undo');undo.type='button';undo.addEventListener('click',function(){prompt.value=original;box.remove();status.textContent='Original prompt restored.';this.scheduleQuote();}.bind(this));box.appendChild(undo);status.textContent='Enhanced prompt applied.';this.scheduleQuote();}.bind(this));keep.addEventListener('click',function(){box.remove();status.textContent='Original prompt kept.';});
  };
  V2Shell.prototype.scheduleQuote=function(){clearTimeout(this.quoteTimer);if(!this.router.current||this.router.current.name!=='create')return;this.quoteTimer=setTimeout(function(){this.previewQuote();}.bind(this),350);};
  V2Shell.prototype.intentFromForm=function(form){var data=form instanceof FormData?form:new FormData(form),mode=this.content.querySelector('[data-ff-action=mode]'),params={};data.forEach(function(value,key){if(key.indexOf('param.')!==0)return;var name=key.slice(6),raw=String(value);params[name]=raw==='true'?true:raw==='false'?false:/^(?:count|duration)$/.test(name)&&/^\d+(?:\.\d+)?$/.test(raw)?Number(raw):raw;});return {mode:mode&&mode.value||'image',modelId:data.get('modelId'),prompt:String(data.get('prompt')||'').trim(),params:params};};
  V2Shell.prototype.previewQuote=async function(){var form=this.content.querySelector('[data-ff-action=generate]'),status=this.content.querySelector('.ff-v2-status');if(!form||!status)return;var intent=this.intentFromForm(form);if(!intent.prompt||!intent.modelId){ns.quotes.invalidate();status.textContent='Choose a model and write a prompt.';return;}status.textContent='Calculating cost…';try{var quote=await ns.generation.prepare(intent);status.textContent='Ready · Cost ✦ '+String(quote.cost!=null?quote.cost:quote.price);}catch(error){if(error&&error.code==='STALE_QUOTE')return;status.textContent=(error&&error.code)||'Cost unavailable';}};
  V2Shell.prototype.enhance=async function(button){
    var prompt=this.content.querySelector('[name=prompt]'),status=this.content.querySelector('.ff-v2-status'),mode=this.content.querySelector('[data-ff-action=mode]'),model=this.content.querySelector('[name=modelId]');if(!prompt||!prompt.value.trim())return;
    button.disabled=true;status.textContent='Enhancing…';try{var result=await ns.genClient.enhance({prompt:prompt.value.trim(),mode:mode&&mode.value,modelId:model&&Number(model.value),reference_kinds:ns.references.snapshot().items.map(function(item){return item.kind;}),format:'text'});if(result&&result.prompt)this.showEnhancePreview(prompt,status,String(result.prompt));else status.textContent='Enhance returned no suggestion.';}catch(error){status.textContent=(error&&error.code)||'Enhance could not complete.';}finally{button.disabled=false;}
  };
  V2Shell.prototype.handleAction=function(event){
    var action=event.target&&event.target.closest&&event.target.closest('[data-ff-action]');if(!action)return;var name=action.dataset.ffAction;
    if(name==='create-mode'){this.draft={dirty:false};this.router.go('create',{mode:action.dataset.value});return;}
    if(name==='open-tool-source'){this.router.go('library',{mode:action.dataset.value});return;}
    if(name==='open-session'){this.draft={dirty:false};ns.sessions.select(action.dataset.value);this.router.go('create',{mode:'image'});return;}
    if(name==='browse-search'&&event.type==='submit'){event.preventDefault();this.router.go('browse',{search:new FormData(action).get('search')||''});return;}
    if(name==='browse-detail'){var browseContext=this.router.current&&this.router.current.context||{};this.router.go('browse',{templateId:action.dataset.value,search:browseContext.search||''});return;}
    if(name==='browse-back'){this.router.go('browse',{search:action.dataset.search||''});return;}
    if(name==='template-import'){this.importTemplate(action.dataset.value,action);return;}
    if(name==='legacy-account'){if(typeof root.openAccountSheet==='function')root.openAccountSheet();return;}
    if(name==='mode'){this.router.go('create',{mode:action.value,prompt:(this.content.querySelector('[name=prompt]')||{}).value||''});return;}
    if(name==='reference'){event.preventDefault();this.chooseReferenceSource(action);return;}
    if(name==='reference-file'&&event.type==='change'){this.addReference(action.files&&action.files[0]);return;}
    if(name==='remove-reference'){ns.references.remove(action.dataset.value);this.draft.dirty=true;this.refreshReferences();this.scheduleQuote();return;}
    if(name==='enhance'){event.preventDefault();this.enhance(action);return;}
    if(name==='generate'&&event.type==='submit'){event.preventDefault();this.generate(new FormData(event.target));return;}
    if(name==='import-result'){this.importResult(action.dataset.value,action);return;}
    if(name==='cancel-job'){this.cancelJob(action.dataset.value,action);return;}
    if(name==='retry-generation'){var item=ns.entities.get('generation',action.dataset.value);if(item){this.draft={dirty:false};this.router.go('create',{mode:item.mode||'image',prompt:item.prompt||'',modelId:item.modelId});}return;}
    if(name==='pin-job'){this.pinJob(action.dataset.value,action);return;}
    if(name==='add-to-project'){this.addToProject(action.dataset.value);return;}
    if(name==='run-operation'){this.runOperation(action.dataset.value,Number(action.dataset.factor)||2,action);return;}
    if(name==='use-library-reference'){this.useLibraryReference(action.dataset.value).catch(function(error){this.message((error&&error.code)||error&&error.message||'Reference unavailable','error');}.bind(this));return;}
    if(name==='project-create'&&event.type==='submit'){event.preventDefault();this.createProject(new FormData(action).get('name'),action);return;}
    if(name==='project-open'){this.router.go('projects',{projectId:action.dataset.value});return;}
    if(name==='projects-back'){this.router.go('projects');return;}
    if(name==='project-rename'){this.renameProject(action.dataset.value,action);return;}
    if(name==='project-delete'){this.deleteProject(action.dataset.value,action);return;}
    if(name==='project-item-remove'){this.removeProjectItem(action.dataset.projectId,action.dataset.value,action);return;}
    if(name==='check-update'){if(typeof root.afCheckForUpdate==='function')root.afCheckForUpdate();else this.message('Update service is unavailable','warning');return;}
    if(name==='clear-diagnostics'){if(ns.Metrics)ns.Metrics.clear();if(ns.SafeLog)ns.SafeLog.clear();try{localStorage.removeItem('af_runtime_errors');}catch(e){}this.message('Local diagnostics cleared','success');return;}
    if(name==='analytics-optout'&&event.type==='change'){try{localStorage.setItem('ff.v2.analytics.optout',action.checked?'1':'0');}catch(e){}if(action.checked&&ns.Metrics)ns.Metrics.clear();return;}
    if(name==='refresh-account'){if(root.AssetFlowAccount&&typeof root.AssetFlowAccount.fetchMe==='function')root.AssetFlowAccount.fetchMe().then(function(){this.refresh();}.bind(this));return;}
    if(name==='sign-out'){ns.accountAdapter.logout();return;}
  };
  V2Shell.prototype.importResult=async function(id,button){var item=ns.entities.get('generation',id);if(!item)return;var media=ns.Surfaces.mediaFor(item);if(!media.url)return this.message('No downloadable result is available','warning');button.disabled=true;button.textContent='Importing…';try{var result=await ns.imports.importAsset({url:media.url,kind:media.kind,ext:media.ext});if(result&&result.ok)this.message(result.addedToComp?'Imported and added at the playhead':'Imported to the Project panel','success');else if(result&&result.unknownOutcome)this.message('Import outcome is unknown. Check the Project panel before trying again.','warning');else this.message((result&&result.reason)||'Import failed','error');}catch(error){this.message((error&&error.message)||'Import failed','error');}finally{button.disabled=false;button.textContent='Import';}};
  V2Shell.prototype.importTemplate=async function(id,button){var item=ns.entities.get('template',id);if(!item)return this.message('Template unavailable','error');if(root.AssetFlowAccount&&typeof root.AssetFlowAccount.isLoggedIn==='function'&&!root.AssetFlowAccount.isLoggedIn()){if(typeof root.openAccountSheet==='function')root.openAccountSheet();return;}if(!root.AssetFlowCatalog||typeof root.AssetFlowCatalog.mergeIntoBrowse!=='function'||typeof root.downloadAll!=='function')return this.message('Template import is unavailable in this build','warning');button.disabled=true;button.textContent='Preparing…';try{root.AssetFlowCatalog.mergeIntoBrowse([item],{append:true});var key='__srv_'+String(id);await root.downloadAll(key);}catch(error){this.message((error&&error.message)||'Template import failed','error');}finally{button.disabled=false;button.textContent='Import to Adobe';}};
  V2Shell.prototype.cancelJob=async function(id,button){button.disabled=true;try{await ns.workspaceClient.cancelJob(id);ns.jobs.stop(id);this.message('Generation cancelled and eligible credits refunded','success');this.refresh();}catch(error){this.message((error&&error.message)||'This generation could not be cancelled','warning');}finally{button.disabled=false;}};
  V2Shell.prototype.pinJob=async function(id,button){var item=ns.entities.get('generation',id),next=!(item&&item.pinned);button.disabled=true;try{await ns.workspaceClient.pinJob(id,next);if(item)item.pinned=next;this.message(next?'Pinned':'Unpinned','success');this.refresh();}catch(error){this.message((error&&error.message)||'Pin update failed','error');}finally{button.disabled=false;}};
  V2Shell.prototype.runOperation=async function(id,factor,button){var item=ns.entities.get('generation',id),media=ns.Surfaces.mediaFor(item),op=ns.models.operationFor(media.kind);if(!item||!op)return this.message('This operation is unavailable','warning');button.disabled=true;try{var job=await ns.operations.run(op,item,factor);this.message(String(op.label||'Operation')+' queued · '+job.id,'success');this.router.go('activity');}catch(error){this.message((error&&error.message)||'Operation could not start','error');}finally{button.disabled=false;}};
  V2Shell.prototype.addToProject=async function(generationId){try{var data=await ns.workspaceClient.projects(),projects=Array.isArray(data&&data.items)?data.items:[];if(!projects.length){this.message('Create a project first','info');this.router.go('projects');return;}var overlay=ns.Surfaces.node('div','ff-v2-modal');overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','Add to project');var card=ns.Surfaces.node('section','ff-v2-modal__card');card.appendChild(ns.Surfaces.node('h2','','Add to project'));var select=ns.Surfaces.node('select','ff-v2-select');projects.forEach(function(project){var option=ns.Surfaces.node('option','',project.name);option.value=project.id;select.appendChild(option);});card.appendChild(select);var actions=ns.Surfaces.node('div','ff-v2-actions'),cancel=ns.Surfaces.node('button','ff-v2-button','Cancel'),add=ns.Surfaces.node('button','ff-v2-primary','Add');cancel.type=add.type='button';actions.appendChild(cancel);actions.appendChild(add);card.appendChild(actions);overlay.appendChild(card);this.root.appendChild(overlay);var close=function(){root.removeEventListener('keydown',onKey);overlay.remove();};var onKey=function(event){if(event.key==='Escape')close();if(event.key==='Tab'){var focusable=[select,cancel,add],at=focusable.indexOf(document.activeElement),next=event.shiftKey?(at<=0?focusable.length-1:at-1):(at>=focusable.length-1?0:at+1);event.preventDefault();focusable[next].focus();}};root.addEventListener('keydown',onKey);cancel.addEventListener('click',close);add.addEventListener('click',async function(){add.disabled=true;try{await ns.workspaceClient.addProjectItem(select.value,'gen',generationId);this.message('Added to project','success');close();}catch(error){this.message((error&&error.message)||'Could not add to project','error');add.disabled=false;}}.bind(this));select.focus();}catch(error){this.message((error&&error.message)||'Projects unavailable','error');}};
  V2Shell.prototype.createProject=async function(name,form){name=String(name||'').trim();if(!name)return;var submit=form.querySelector('[type=submit]');if(submit)submit.disabled=true;try{await ns.workspaceClient.createProject(name);this.message('Project created','success');this.router.go('projects');}catch(error){this.message((error&&error.message)||'Project could not be created','error');}finally{if(submit)submit.disabled=false;}};
  V2Shell.prototype.renameProject=async function(id,button){var item=ns.entities.get('project',id),name=root.prompt?root.prompt('Project name',item&&item.name||''):null;if(name==null||!String(name).trim())return;button.disabled=true;try{await ns.workspaceClient.renameProject(id,String(name).trim());this.message('Project renamed','success');this.router.go('projects');}catch(error){this.message((error&&error.message)||'Project could not be renamed','error');}finally{button.disabled=false;}};
  V2Shell.prototype.deleteProject=async function(id,button){if(root.confirm&&!root.confirm('Delete this project? Generated files and marketplace assets will remain in their original locations.'))return;button.disabled=true;try{await ns.workspaceClient.deleteProject(id);this.message('Project deleted','success');this.router.go('projects');}catch(error){this.message((error&&error.message)||'Project could not be deleted','error');}finally{button.disabled=false;}};
  V2Shell.prototype.removeProjectItem=async function(projectId,itemId,button){button.disabled=true;try{await ns.workspaceClient.removeProjectItem(projectId,itemId);this.message('Removed from project','success');this.router.go('projects',{projectId:projectId});}catch(error){this.message((error&&error.message)||'Item could not be removed','error');}finally{button.disabled=false;}};
  V2Shell.prototype.chooseReferenceSource=function(trigger){var overlay=ns.Surfaces.node('div','ff-v2-modal');overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','Add reference');var card=ns.Surfaces.node('section','ff-v2-modal__card');card.appendChild(ns.Surfaces.node('h2','','Add reference'));var sources=[['File','file'],['Adobe Project selection','project'],['Timeline current frame','frame'],['Library result','library']],actions=ns.Surfaces.node('div','ff-v2-ref-sources'),self=this;function close(){root.removeEventListener('keydown',key);overlay.remove();trigger.focus();}function key(event){if(event.key==='Escape')close();}sources.forEach(function(source){var item=ns.Surfaces.node('button','ff-v2-button',source[0]);item.type='button';item.addEventListener('click',function(){close();if(source[1]==='file'){var picker=self.content.querySelector('[data-ff-action=reference-file]');if(picker)picker.click();}else if(source[1]==='library'){var prompt=self.content.querySelector('[name=prompt]'),model=self.content.querySelector('[name=modelId]'),mode=self.content.querySelector('[data-ff-action=mode]');self.referenceReturn={prompt:prompt&&prompt.value||'',modelId:model&&model.value||'',mode:mode&&mode.value||'image'};self.router.go('library',{referenceSelect:true});}else self.addHostReference(source[1]==='project'?'getSelection':'captureCurrentFrame');});actions.appendChild(item);});card.appendChild(actions);overlay.appendChild(card);this.root.appendChild(overlay);root.addEventListener('keydown',key);actions.querySelector('button').focus();};
  V2Shell.prototype.addHostReference=async function(command){var status=this.content.querySelector('.ff-v2-status');status.textContent='Reading Adobe source…';try{var result=await ns.hostCommands.run(command,{}),filePath=result.mediaPath||result.path||'',fs=typeof require==='function'?require('fs'):null;if(!fs||!filePath)throw new Error('Adobe did not return a readable file');var bytes=fs.readFileSync(filePath),ext=String(filePath).split('.').pop().toLowerCase(),mime=/^(png)$/.test(ext)?'image/png':/^(jpe?g)$/.test(ext)?'image/jpeg':/^(webp)$/.test(ext)?'image/webp':/^(mp4|m4v)$/.test(ext)?'video/mp4':/^(mov)$/.test(ext)?'video/quicktime':/^(wav)$/.test(ext)?'audio/wav':'audio/mpeg',kind=mime.split('/')[0],modelSelect=this.content.querySelector('[name=modelId]'),model=modelSelect&&ns.models.get(modelSelect.value),role=ns.references.nextRole(model,kind),gate=ns.references.canAdd(model,kind,role);if(!gate.ok)throw Object.assign(new Error(gate.reason),{code:gate.reason});var saved=await ns.workspaceClient.uploadReference('data:'+mime+';base64,'+bytes.toString('base64'));ns.references.add({id:saved.id||saved.referenceId,kind:kind,role:role,mime:saved.contentType||mime,size:saved.bytes||bytes.length,url:saved.url||null,handle:saved.id||saved.referenceId});this.draft.dirty=true;status.textContent=(role==='start-frame'?'Start frame':role==='end-frame'?'End frame':'Reference')+' ready';this.refreshReferences();this.scheduleQuote();}catch(error){status.textContent=(error&&error.code)||error&&error.message||'Adobe reference failed';}};
  V2Shell.prototype.useLibraryReference=async function(id){var item=ns.entities.get('generation',id),back=this.referenceReturn||{mode:'image'},fresh=await ns.genClient.job(id),media=ns.Surfaces.mediaFor(fresh||item),kind=media.kind==='voice'||media.kind==='sfx'?'audio':media.kind,mime=kind==='image'?'image/png':kind==='video'?'video/mp4':'audio/mpeg';this.router.go('create',back);setTimeout(function(){try{var model=ns.models.get(back.modelId),role=ns.references.nextRole(model,kind),gate=ns.references.canAdd(model,kind,role);if(!gate.ok)throw Object.assign(new Error(gate.reason),{code:gate.reason});ns.references.add({id:'library_'+id,saved:false,kind:kind,role:role,mime:mime,size:1,url:media.url});this.draft.dirty=true;var status=this.content.querySelector('.ff-v2-status');if(status)status.textContent=(role==='start-frame'?'Start frame':role==='end-frame'?'End frame':'Library reference')+' ready';this.refreshReferences();this.scheduleQuote();}catch(error){this.message((error&&error.code)||'Reference unavailable','error');}}.bind(this),0);};
  V2Shell.prototype.addReference=function(file){if(!file)return;var status=this.content.querySelector('.ff-v2-status'),kind=String(file.type||'').split('/')[0],modelSelect=this.content.querySelector('[name=modelId]'),model=modelSelect&&ns.models.get(modelSelect.value),role=ns.references.nextRole(model,kind),gate=ns.references.canAdd(model,kind,role);if(!gate.ok){status.textContent=gate.reason;return;}status.textContent='Uploading '+(role==='start-frame'?'start frame':role==='end-frame'?'end frame':'reference')+'…';var reader=new FileReader();reader.onload=function(){ns.workspaceClient.uploadReference(String(reader.result||'')).then(function(saved){ns.references.add({id:saved.id||saved.referenceId,kind:kind,role:role,mime:saved.contentType||file.type,size:saved.bytes||file.size,url:saved.url||null,expiresAt:saved.expiresAt||null,handle:saved.id||saved.referenceId});this.draft.dirty=true;status.textContent=(role==='start-frame'?'Start frame':role==='end-frame'?'End frame':'Reference')+' ready';this.refreshReferences();this.scheduleQuote();}.bind(this)).catch(function(error){status.textContent=(error&&error.code)||'Reference upload failed';});}.bind(this);reader.onerror=function(){status.textContent='Reference could not be read';};reader.readAsDataURL(file);};
  V2Shell.prototype.generate=async function(form){var status=this.content.querySelector('.ff-v2-status'),submit=this.content.querySelector('[type=submit]'),intent=this.intentFromForm(form);if(!intent.prompt||!intent.modelId)return;submit.disabled=true;try{status.textContent='Calculating cost…';await ns.generation.prepare(intent);status.textContent='Submitting…';var job=await ns.generation.submit();job.prompt=intent.prompt;job.mode=intent.mode;job.modelId=intent.modelId;job.params=intent.params;this.draft.dirty=false;status.textContent='Queued · '+job.id;var self=this;ns.jobs.poll(job.id,2500,function(next){status.textContent=String(next.status||'processing');if(/completed|done|failed|canceled|refunded/.test(String(next.status||''))){rememberResult(next,intent);if(/completed|done/.test(String(next.status||'')))self.message('Generation completed','success');}});}catch(error){status.textContent=(error&&error.code)||'Generation failed';}finally{submit.disabled=false;}};
  V2Shell.prototype.start=function(){if(this.started)return;this.started=true;this.mount();this.register();var self=this;this.resources.listen(this.root,'click',function(event){var target=event.target.closest('[data-ff-v2-route]');if(target){event.preventDefault();if(self.canLeaveCreate(target.dataset.ffV2Route)){self.draft.dirty=false;self.router.go(target.dataset.ffV2Route);}return;}self.handleAction(event);});this.resources.listen(this.root,'change',function(event){self.handleAction(event);if(event.target&&(event.target.name==='modelId'||String(event.target.name||'').indexOf('param.')===0))self.scheduleQuote();});this.resources.listen(this.root,'input',function(event){if(event.target&&event.target.name==='prompt'){self.draft.dirty=!!String(event.target.value||'').trim();self.scheduleQuote();}});this.resources.listen(this.root,'submit',function(event){self.handleAction(event);});this.router.go('home');};
  V2Shell.prototype.stop=function(){if(!this.started)return Promise.resolve();this.started=false;clearTimeout(this.quoteTimer);this.resources.dispose();if(this.root)this.root.remove();this.root=null;var legacy=document.getElementById('container');if(legacy)legacy.hidden=false;return this.router.dispose();};
  ns.V2Shell=V2Shell;
})(typeof window!=='undefined'?window:globalThis);
