(function(root){
  'use strict';
  var ns=root.FFVNext=root.FFVNext||{};
  function parse(raw){if(raw&&typeof raw==='object')return raw;try{return JSON.parse(String(raw||''));}catch(e){return {ok:false,error:'HOST_INVALID_RESPONSE',reason:'Adobe host returned an invalid response'};}}
  function RuntimeHostAdapter(options){options=options||{};this.download=options.download||function(url,ext){if(typeof root.aiDownloadToTemp!=='function')return Promise.reject(Object.assign(new Error('Download bridge unavailable'),{code:'DOWNLOAD_BRIDGE_UNAVAILABLE'}));return root.aiDownloadToTemp(url,ext);};this.evaluate=options.evaluate||function(script,opts){if(typeof root.hostEvalGuarded!=='function')return Promise.reject(Object.assign(new Error('Host bridge unavailable'),{code:'HOST_BRIDGE_UNAVAILABLE'}));return root.hostEvalGuarded(script,opts);};this.operations={};}
  RuntimeHostAdapter.prototype.capabilities=function(){var raw=root.AF_HOST_CAPABILITIES||{};return {getSelection:!!raw.projectReference,captureCurrentFrame:!!raw.currentFrameReference,importMedia:typeof root.__adobe_cep__!=='undefined',importTemplate:raw.projectTemplateImport!==false,reconcileImport:true,insertAtPlayhead:!!raw.timelineReference,getProjectContext:true,removeCreatedItemByStableId:!!raw.safeRemoveById};};
  RuntimeHostAdapter.prototype.importMedia=async function(payload){var op=String(payload.operationId||''),kind=String(payload.kind||'image'),fallback=kind==='image'?'png':kind==='video'?'mp4':'mp3',ext='.'+String(payload.ext||fallback).replace(/^\./,'');this.operations[op]={operationId:op,status:'downloading',startedAt:Date.now()};try{var filePath=payload.filePath||await this.download(String(payload.url||''),ext);this.operations[op].status='host_pending';this.operations[op].filePath=filePath;var result=parse(await this.evaluate('importMediaFromPath('+JSON.stringify(filePath)+')',{label:'Importing media',softMs:15000,hardMs:180000}));if(result&&result.ok){this.operations[op]=Object.assign({},this.operations[op],{status:'completed',completedAt:Date.now(),result:result});return result;}if(result&&/timeout|cancelled/.test(String(result.error||''))){this.operations[op]=Object.assign({},this.operations[op],{status:'unknown_outcome',result:result});return Object.assign({},result,{unknownOutcome:true,operationId:op});}this.operations[op]=Object.assign({},this.operations[op],{status:'failed',completedAt:Date.now(),result:result});return result;}catch(error){this.operations[op]=Object.assign({},this.operations[op],{status:'failed',completedAt:Date.now(),result:{ok:false,error:error&&error.code||'IMPORT_FAILED',reason:error&&error.message||'Import failed'}});throw error;}};
  RuntimeHostAdapter.prototype.reconcileImport=function(payload){var record=this.operations[String(payload.operationId||'')];if(!record)return Promise.resolve({ok:false,status:'not_found',operationId:payload.operationId});if(record.status==='completed')return Promise.resolve(Object.assign({ok:true,status:'completed'},record.result||{}));return Promise.resolve({ok:false,status:record.status,unknownOutcome:record.status==='unknown_outcome'||record.status==='host_pending',operationId:record.operationId});};
  RuntimeHostAdapter.prototype.call=async function(script,label){var result=parse(await this.evaluate(script,{label:label,softMs:10000,hardMs:60000}));if(!result||!result.ok){var error=new Error(result&&result.reason||result&&result.message||'Host command failed');error.code=result&&result.error||'HOST_COMMAND_FAILED';throw error;}return result;};
  RuntimeHostAdapter.prototype.run=function(name,payload){if(name==='importMedia')return this.importMedia(payload||{});if(name==='reconcileImport')return this.reconcileImport(payload||{});if(name==='getSelection')return this.call('getSelectedProjectReference()','Reading Project selection');if(name==='captureCurrentFrame')return this.call('exportTimelineFrame()','Capturing current frame');if(name==='getProjectContext')return this.call('listProjectFootage()','Reading Adobe project');return Promise.reject(Object.assign(new Error('Host command has no runtime adapter'),{code:'HOST_COMMAND_UNIMPLEMENTED'}));};
  ns.RuntimeHostAdapter=RuntimeHostAdapter;
})(typeof window!=='undefined'?window:globalThis);
